dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-09/run.sh |  bash
notifications:
  slack:
    secure: BQJmT4aIkYaIAx6nLqGkWcq/r0OVRExEOV8P4njd5aj3g2Qv6MzekFMd2R3Xwn/c8hgCXrdq5eO3Rg47HXRi80BTj9DDpQXNzlMr24U2xjOtRjnqLrnXlwu3A4bTYoG3rYaylqvRLLyO4hS32ehjJN6Q+Bo5MBzKlCExhI+NqRf8G+rl0JJe+bNWsHQaxpmL/9KXIh+WHRLC33g1maX+WheIXPbn/Y5QErNc0KiEnLqCur53n2+/rxjklf6ud2jmiVTyQk2fX8w44pozYODr9wMMby1fRinX5M/uD5CIl1Qbqh0/EtX0rirBFGk0AtZTyI/ojkABW64bXjae5RTdfyqUUgl9tqx2D5Uy4WZ16fGVMR28GWwwmX8/Y7xwPaunmTTpVWv5pL1qs/NPb62UznjmLb4Pxiy+VyRaWWud9LijZkgO5zfT1tgG0iU5LpN35ny90OW0/vho4xDw6LwWiYZLdFJyO/KSnfDoSlLUwtH8zg2eNcbxJD81y35iu14bqr7cVM0Sg2KitX8G4Wx8mUCnHqQiVhqojaJmUngz7IJZ/JMQF9pmqUidByFYCtRwMlqf9jqxVSAMa/j1Q2FKlnay0UNnPBstaFibCu6AAI6CsD5FxKNbn17Xv8Yf15TRt/zKFF01zaZvSet7lTsvYnU2SPOPG9cuQ6KSTQxGq+k=
